### ISSUE TITLE
func_adl_servicex no longer working with servicex

### ISSUE THREAD

**Issue by andresailer** [iris-hep/func_adl_servicex#61]
Dear Developers,

The latest version of func_adl_servicex does not work with the latest version of the servicex package.

```
$ source /cvmfs/sft.cern.ch/lcg/views/dev3python312/latest/x86_64-el9-gcc13-opt/setup.sh
$ python -c "import func_adl_servicex"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python312/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/func_adl_servicex/__init__.py", line 3, in <module>
    from .ServiceX import ServiceXSourceUpROOT, ServiceXSourceXAOD, ServiceXSourceCMSRun1AOD, FuncADLServerException  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python312/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/func_adl_servicex/ServiceX.py", line 10, in <module>
    from servicex import ServiceXDataset
ImportError: cannot import name 'ServiceXDataset' from 'servicex' (/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python312/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages/servicex/__init__.py
```

```
pip show servicex
Name: servicex
Version: 3.1.0
Summary: Python SDK and CLI Client for ServiceX
Home-page: 
Author: 
Author-email: Ben Galewsky <bengal1@illinois.edu>, Gordon Watts <gwatts@uw.edu>
License: BSD-3-Clause
Location: /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python312/Thu/x86_64-el9-gcc13-opt/lib/python3.12/site-packages
Requires: aiofile, aiohttp-retry, filelock, func-adl, google-auth, httpx, make-it-sync, miniopy-async, pydantic, pyyaml, qastle, requests, rich, ruamel-yaml, tenacity, tinydb, typer, types-pyyaml
Required-by: func_adl_servicex
```

Will there be an update for this package, or is it considered obsolete?

Thanks!

**Comment by ponyisi** [comment]
Hi @andresailer , while waiting for @gordonwatts to comment, I assume you are trying to run some particular ServiceX query? I may be able to help (almost certainly we need to do an update to the latest API).

**Comment by andresailer** [comment]
Hi @ponyisi 

Thanks for your offer, however, we are providing the LCG software stacks (/cvmfs/sft.cern.ch/lcg), and a user requested the installation of func_adl_servicex in the past. While updating to the latest packages to make things work with python 3.12 we noticed that one can no longer use the func_adl_servicex package the import just doesn't work.
Thus we would either need an update, or drop it form the stacks, if it is no longer needed.

Cheers!

**Comment by ponyisi** [comment]
OK, yes, this package is not compatible with the latest `servicex` Python package version. @gordonwatts should still comment but it should be safe to remove from the LCG stack.

**Comment by gordonwatts** [comment]
Sorry - I would remove this. With the latest version of the front end, we pulled some of the functionality into the frontend package. There is a chance it will be removed later. We should put a comment in teh README on that package.

Very sorry for the confusion!!
